#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Rui Suzuki
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime
from datetime import timedelta

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

x = 0

for line in sys.stdin:
    line = line.rstrip()
    x += tonum(line)

rightnow = datetime.datetime.now()
today = rightnow.date()
futu = today + timedelta(x)

print(futu)

##y = futu.year
##m = futu.month
##d = futu.day

##if ( (y == 2023) & (m == 1) & (d == 27) ):
##    print("It's time for Graduation thesis presentation")
##elif ( (m == 3) & (d == 2) ):
##    print("HAPPY BIRTHDAY")
##elif ( (m == 12) & (d == 25) ):
##    print("MERRY CHRISTMAS")
##elif ( (m == 1) & (d == 1) ):
##    print("HAPPY NEW YEAR")
##else:
##    print("NOTHING SPECIAL, BUT HAVE A NICE DAY")

