#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Rui Suzuki
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime
from datetime import timedelta

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

x = 0

for line in sys.stdin:
    line = line.rstrip()
    x += tonum(line)

rightnow = datetime.datetime.now()
today = rightnow.date()
futu = today + timedelta(x)

print(futu)

