#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Rui Suzuki
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime

##def tonum(s):
##    try:
##        return int(s)
##    except:
##        return float(s)

today = datetime.datetime.now()

print(today)

##ans = 0.0

##for line in sys.stdin:
##    line = line.rstrip()
##    ans += tonum(line)

##print(ans)

