#!/bin/bash -xv
# SPDX-FileCopyrightText: 2022 Rui Suzuki
#SPDX-License -Identifier: BSD-3-Clause

ng(){
	echo Error at line $1
	res=1
}

res=0

### I/O Test ###
out=$(seq 5 | ./plus)
[ "${out}" = 15.0 ] || ng $LINENO
[ "$res" = 0 ] && echo OK

exit $res

