#!/bin/bash -xv
#SPDX-FileCopyrightText: 2022 Rui Suzuki
#SPDX-License -Identifier: BSD-3-Clause

ng(){
	echo Error at line $1
	res=1
}

res=0

### I/O Test #############################################################
## REMINDER								##
##									##
## THIS TEST PROGRAM NEED TO BE CHANGED TO WHEN YOUR TEST WAS CONDUCTED ##
##									##
##########################################################################

${out}=$( seq 0 | ./plus )

[ "${out}"="2022-12-07" ] || ng $LINENO
### Strange Input ###
##out=$(echo A | ./plus)
##[ "$?" = 1 ] || ng $LINENO
##[ "${out}" = "" ] || ng $LINENO
##out=$(echo | ./plus)
##[ "$?" = 1 ] || ng $LINENO
##[ "${out}" = "" ] || ng $LINENO
##[ "$res" = 0 ] && echo OK
exit $res

