name: test      # Name of this workflow
on: push        # When this workflow runs
jobs:           # Job list
        test:   # Job named test
                runs-on: ubuntu-latest          # Runing environmwnt
                strategy:
                        matrix:
                                python-version: ["3.8" ]
                steps:                          # Steps
                - uses: actions/checkout@v3     # https://github.com/actions/checkout version3
                - name: All test                # Job name
                  run: bash -xv ./test          # Run the shell script of test
